// 코드 속 도트 그림. 한 글자 = 한 도트, 색은 palette.js.
import { PALETTE } from "./palette.js?v=7fd5be7-1791541871";

export const SPRITES = {
  egg: [
    "......kkkk......",
    "....kkwwwwkk....",
    "...kwwwwwwwwk...",
    "..kwwppwwwwwwk..",
    "..kwwppwwwggwk..",
    ".kwwwwwwwwggwwk.",
    ".kwwwwwwwwwwwwk.",
    ".kwggwwwwwwwwwk.",
    "kwwggwwwwppwwwwk",
    "kwwwwwwwwppwwwwk",
    "kwwwwwwwwwwwwwwk",
    "kwwwwppwwwwwggwk",
    "kwwwwppwwwwwggwk",
    ".kwwwwwwwwwwwwk.",
    ".kswwwwwwwwwwsk.",
    "..kssswwwwsssk..",
    "...kkssssssskk..",
    ".....kkkkkk.....",
  ],
  eggRainbow: [
    "......kkkk......",
    "....kkwwwwkk....",
    "...kwwwwwwwwk...",
    "..kwwwwwwwwwwk..",
    "..krrrrrrrrrrk..",
    ".kroooooooooork.",
    ".kooooooooooook.",
    ".kyyyyyyyyyyyyk.",
    "kwwwwwwwwwwwwwwk",
    "kggggggggggggggk",
    "kwwwwwwwwwwwwwwk",
    "kbbbbbbbbbbbbbbk",
    "kwwwwwwwwwwwwwwk",
    ".kvvvvvvvvvvvvk.",
    ".kswwwwwwwwwwsk.",
    "..kssswwwwsssk..",
    "...kkssssssskk..",
    ".....kkkkkk.....",
  ],
  // 아래 행동 버튼 아이콘 (10칸 폭)
  iconFood: [
    "...w..w...",
    "..w..w....",
    "..wwwwwww.",
    ".kkkkkkkk.",
    ".kooooook.",
    "..kooook..",
    "...kkkk...",
  ],
  iconPlay: [
    "...kkkk...",
    "..kyyrrk..",
    ".kyyyrrrk.",
    ".krryyyyk.",
    ".krrryyyk.",
    "..krryyk..",
    "...kkkk...",
  ],
  iconWash: [
    "....kk....",
    "...kbbk...",
    "..kbbbbk..",
    ".kbwbbbbk.",
    ".kbwbbbbk.",
    ".kbbbbbbk.",
    "..kbbbbk..",
    "...kkkk...",
  ],
  iconLight: [
    "...kkkk...",
    "..kyyyyk..",
    ".kyywyyyk.",
    ".kyyyyyyk.",
    "..kyyyyk..",
    "...kyyk...",
    "...kNNk...",
    "...kkkk...",
  ],
  iconMedicine: [
    "..kkkkkk..",
    ".kpppwwwk.",
    "kppppwwwwk",
    "kppppwwwwk",
    ".kpppwwwk.",
    "..kkkkkk..",
  ],
  // ----- 애니메이션 소품 -----
  bowlFull: [
    "...wwww...",
    ".wwwwwwww.",
    "kkkkkkkkkk",
    "kbbbbbbbbk",
    ".kbbbbbbk.",
    "..kkkkkk..",
  ],
  bowlHalf: [
    "..........",
    "...wwwww..",
    "kkkkkkkkkk",
    "kbbbbbbbbk",
    ".kbbbbbbk.",
    "..kkkkkk..",
  ],
  bowlEmpty: [
    "..........",
    "..........",
    "kkkkkkkkkk",
    "kbbbbbbbbk",
    ".kbbbbbbk.",
    "..kkkkkk..",
  ],
  cookie: [
    ".kkkk.",
    "koonok",
    "kooook",
    "knoook",
    "koonok",
    ".kkkk.",
  ],
  // ---- 화폐·메뉴 아이콘 ----
  coinStar: [
    "..kkkk..",
    ".kyyyyk.",
    "kyywyyYk",
    "kywyyyYk",
    "kyyyyyYk",
    "kyyyyYYk",
    ".kYYYYk.",
    "..kkkk..",
  ],
  coinGem: [
    ".kk.kk.",
    "kpwkPPk",
    "kppppPk",
    ".kpppk.",
    "..kpk..",
    "...k...",
  ],
  iconDeco: [
    "...kkkkkk...",
    "..kppppppk..",
    "..kpwppppk..",
    "kkkkkkkkkkkk",
    "kpkPPPPPPkpk",
    "kpkPPPPPPkpk",
    "kpkkkkkkkkpk",
    "kkkkkkkkkkkk",
    ".kN......Nk.",
  ],
  iconShop: [
    "...kkkkkk...",
    "..k......k..",
    ".kkkkkkkkkk.",
    ".kppppppppk.",
    ".kpwppppppk.",
    ".kppkkkkppk.",
    ".kppkyykppk.",
    ".kppppppppk.",
    ".kkkkkkkkkk.",
  ],
  iconBook: [ // 도감: 펼친 책(가운데 분홍 책등, 양쪽 책장에 글줄). 디자인 리뷰 서브에이전트 2차 사양
    ".kkk....kkk.",
    ".kwwk..kwwk.",
    "kwwwwPPwwwwk",
    "kwwwwPPwwwwk",
    "kpppwPPwpppk",
    "kwwwwPPwwwwk",
    "kpppwPPwpppk",
    "kwwwwPPwwwwk",
    "kkkkkkkkkkkk",
  ],
  iconGift: [
    "..kk..kk..",
    ".krrkkrrk.",
    "kkkkkkkkkk",
    "kpppkkpppk",
    "kkkkkkkkkk",
    ".kppkkppk.",
    ".kppkkppk.",
    ".kppkkppk.",
    ".kkkkkkkk.",
  ],
  // ---- 머리 장식(상점) ----
  hatRibbon: [
    ".kk...kk.",
    "kPpk.kpPk",
    "kPppkppPk",
    "kPpkkkpPk",
    ".kk.k.kk.",
  ],
  hatStraw: [
    "....kkkk....",
    "...kyYYyk...",
    "...kyyyyk...",
    "..kkrrrrkk..",
    "kkyyyyyyyykk",
    "kYYYYYYYYYYk",
    ".kkkkkkkkkk.",
  ],
  hatGlasses: [
    ".kkk...kkk.",
    "kbwbk.kbwbk",
    "kbbbkkkbbbk",
    ".kkk...kkk.",
  ],
  hatCrown: [
    "k...k...k",
    "kk.kyk.kk",
    "kykyyykyk",
    "kyyyryyyk",
    "kYYYYYYYk",
    "kkkkkkkkk",
  ],
  hatFlower: [
    ".kkk.......kkk.",
    "kpPpk.kkk.kvVvk",
    "kPyPkkyYykkVyVk",
    "kpPpkkYyYkkvVvk",
    ".kkkGkkykkGkkk.",
    "..kGGGGkGGGGk..",
    "...kkkkkkkkk...",
  ],
  // ---- 특별한 날 모자 ----
  santaHat: [
    "......kkk...",
    "....kkrrkww.",
    "...krrrrkwwk",
    "..krrrrrrk..",
    ".krrrrrrrrk.",
    "kwwwwwwwwwwk",
    "kwwwwwwwwwwk",
    ".kkkkkkkkkk.",
  ],
  pumpkinHat: [
    ".....kGk....",
    "....kGk.....",
    "..kkkkkkkk..",
    ".kooOooOook.",
    "kooOookooOok",
    "koOkoooookOk",
    "kooOoooOooOk",
    ".kkkkkkkkkk.",
  ],
  partyHat: [
    ".....y.....",
    "....kyk....",
    "....kbk....",
    "...kbybk...",
    "...kpppk...",
    "..kybbbyk..",
    "..kppyppk..",
    ".kbbbybbbk.",
    "kkkkkkkkkkk",
  ],
  heartClip: [
    ".kk.kk.",
    "krrkrrk",
    "krrrrrk",
    ".krrrk.",
    "..krk..",
    "...k...",
  ],
  // ---- 놀이 소품 ----
  bigBubble: [
    "..bbbbb..",
    ".b.....b.",
    "b.ww....b",
    "b.w.....b",
    "b.......b",
    "b.......b",
    "b......wb",
    ".b....w..",
    "..bbbbb..",
  ],
  box: [
    "kkkkkkkkkkkk",
    "kOooooooooOk",
    "kkkkkkkkkkkk",
    "kooooOOoooOk",
    "kooooOOooook",
    "kooooOOooook",
    "kooooOOooook",
    "kooooooooOOk",
    "kOOOOOOOOOOk",
    "kkkkkkkkkkkk",
  ],
  basket: [
    "...kkkkkk...",
    "..k......k..",
    ".k........k.",
    "kkkkkkkkkkkk",
    "kyYyYyYyYyYk",
    "kYyYyYyYyYyk",
    ".kyYyYyYyYk.",
    ".kYyYyYyYyk.",
    "..kyYyYyYk..",
    "..kkkkkkkk..",
  ],
  plant: [
    "...k..k.....",
    "..kGk.kGk...",
    ".kGgGkGgGk..",
    ".kGgGGGgGk..",
    "..kGgGgGkGk.",
    "kGkkGGGkkgGk",
    "kgGGkGkGGGk.",
    ".kkkkkkkkkk.",
    ".koooooooOk.",
    ".kOOOOOOOOk.",
    "..koooooOk..",
    "..kkkkkkkk..",
  ],
  ring: [
    "...wwwww...",
    ".ww.....ww.",
    "w.........w",
    ".ww.....ww.",
    "...wwwww...",
  ],
  ringOn: [
    "..yYYYYYy..",
    ".YyyyyyyyY.",
    "Yy.......yY",
    ".YyyyyyyyY.",
    "..yYYYYYy..",
  ],
  duck: [
    "..kkk...",
    ".kyyyk..",
    ".kykyko.",
    ".kyyykoo",
    "kkyyyyk.",
    "kyyyyyyk",
    ".kyyyyk.",
    "..kkkk..",
  ],
  ball: [
    "..kkkk..",
    ".kyyrrk.",
    "kyyyrrrk",
    "kyyyyrrk",
    "krryyyyk",
    "krrryyyk",
    ".krryyk.",
    "..kkkk..",
  ],
  heart: [
    ".PP.PP.",
    "PppPppP",
    "PpppppP",
    ".PpppP.",
    "..PpP..",
    "...P...",
  ],
  sparkle: [
    "..y..",
    "..y..",
    "yywyy",
    "..y..",
    "..y..",
  ],
  bubble: [
    ".bbb.",
    "bw..b",
    "b...b",
    "b...b",
    ".bbb.",
  ],
  drop: [
    ".b.",
    "bbb",
    "bwb",
    ".b.",
  ],
  letter: [
    "kkkkkkkkkk",
    "kwwwwwwwwk",
    "kkwwwwwwkk",
    "kwkkwwkkwk",
    "kwwwkrkwwk",
    "kwwwwwwwwk",
    "kkkkkkkkkk",
  ],
  bigStar: [
    "...Y...",
    "..YYY..",
    "YYYwYYY",
    ".YYYYY.",
    "..YYY..",
    ".YY.YY.",
    "Y.....Y",
  ],
  crumb: [
    "ww",
    "ws",
  ],
  tear: [
    "b",
    "b",
  ],
  puff: [
    "..ss...",
    ".swwss.",
    "swwwwws",
    ".sssss.",
  ],
  hungryBubble: [
    "..kkkkkkkk..",
    ".kwwwwwwwwk.",
    "kwwwwwwwwwwk",
    "kwwowowwwwwk",
    "kwkkkkkkkwwk",
    "kwwkooookwwk",
    ".kwwkkkkwwk.",
    "..kkkkkkkk..",
    "....kwk.....",
    ".....k......",
  ],
};

export function spriteSize(sprite) {
  return { w: sprite[0].length, h: sprite.length };
}

export function drawSprite(ctx, sprite, x, y, scale = 1) {
  for (let row = 0; row < sprite.length; row++) {
    const line = sprite[row];
    for (let col = 0; col < line.length; col++) {
      const color = PALETTE[line[col]];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(Math.round(x + col * scale), Math.round(y + row * scale), scale, scale);
    }
  }
}
